package:
    name:           hidev-phpunit
    namespace:      hidev\phpunit
    headline:       HiDev PHPUnit
    title:          PHPUnit plugin for HiDev
    type:           yii2-extension
    keywords:       phpunit, hidev, plugin
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin enables [PHPUnit](https://phpunit.de/) support for HiDev.

        Provides usual PHPUnit operations:
        - generating phpunit.xml.dist
        - generating basic unit tests (in progress)
        - running tests
        - tries to create your tests compatible with Codeception

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-hiqdev:        "*@dev"
    hiqdev/hidev-travis-ci:     "*@dev"
    hiqdev/hidev-codeception:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
