package:
    name:           hidev-phpunit
    namespace:      hidev\phpunit
    headline:       HiDev PHPUnit
    title:          PHPUnit plugin for HiDev
    type:           yii2-extension
    keywords:       phpunit, hidev, plugin
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin enables [PHPUnit](https://phpunit.de/) support for HiDev.

        Provides usual PHPUnit operations:
        - generating phpunit.xml.dist
        - running tests
        - tries to create your tests compatible with Codeception
        - generating skeleton tests with [phpunit-skeleton-generator](https://github.com/sebastianbergmann/phpunit-skeleton-generator) (in progress)
        - coverage report (in progress)

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-readme:        "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-composer:      "*@dev"
    hiqdev/hidev-travis-ci:     "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
